# Generated by Django 3.0.6 on 2020-06-01 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MultiCredCardAPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='user',
            new_name='User',
        ),
    ]
