# Generated by Django 3.0.6 on 2020-06-02 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MultiCredCardAPI', '0002_auto_20200531_2328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='MaxLimit',
            new_name='LimitDefinedByClient',
        ),
        migrations.AddField(
            model_name='creditcard',
            name='AvailableCredit',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='creditcard',
            name='Limit',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='creditcard',
            name='Password',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
