# Generated by Django 3.0.6 on 2020-06-02 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MultiCredCardAPI', '0003_auto_20200602_0312'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcard',
            name='PaymentDueDate',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
